### ISSUE TITLE
Shall the Header or a separate menu show additional content?

### ISSUE THREAD

**Issue by bloodmandarin** [Mindful-Meerkats/textMVP#3]
In #2 I added What is Meeka/Mindful Meerkats to the header... Maybe we should have that in a separate menu?

**Comment by jjwedemyer** [comment]
Please just add a picture of a mockup for both

**Comment by bloodmandarin** [comment]
I am more excited about the Hidden menu now, because people should only find it if they look around. So let's do the "Burger"-menu as seen in #2 .
